'use strict';
const P=window.PROJECT, $=s=>document.querySelector(s), arts=P.artifacts;
const storageKey='filetools-feedback:'+P.project_id;
let feedbackBase=0, comments=[], loading=Promise.resolve(), tokens={left:0,right:0};
const notice=s=>{$('#status').textContent=s;};
function stable(x){if(Array.isArray(x))return '['+x.map(stable).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';return JSON.stringify(x);}
function artifact(side){return arts.find(a=>a.artifact_id===$('#'+side+'Artifact').value);}
function position(side){let a=artifact(side);return a.pages[Number($('#'+side+'Position').value)]||{locator:{kind:'document'}};}
function identity(){let a=artifact('right'),r=artifact('left');return {project_id:P.project_id,artifact_id:a.artifact_id,artifact_sha256:a.sha256,locator:position('right').locator,reference_artifact_id:r.artifact_id,reference_sha256:r.sha256,reference_locator:position('left').locator};}
function key(c){return stable([c.artifact_id,c.artifact_sha256,c.locator,c.reference_artifact_id,c.reference_sha256,c.reference_locator]);}
let active=null;
function save(){if(!active)return;let i=comments.findIndex(c=>key(c)===key(active)),text=$('#comment').value;if(i>=0&&comments[i].text===text)return;if(i<0&&!text)return;let c={...active,text,updated_at:new Date().toISOString()};if(i<0)comments.push(c);else comments[i]=c;try{localStorage.setItem(storageKey,JSON.stringify(comments));notice('草稿已存本机；请导出备份。');}catch{notice('浏览器存储不可用，请导出备份。');}}
function loadComment(){active=identity();$('#comment').value=(comments.find(c=>key(c)===key(active))||{}).text||'';}
function knownLocator(a,l){return l&& (stable(l)===stable({kind:'document'})||a.pages.some(p=>stable(p.locator)===stable(l)));}
function validate(data){if(data.schema!=='filetools-artifact-feedback-v1'||data.project_id!==P.project_id||data.project_revision!==P.revision||!['human','developer-agent'].includes(data.reviewer_type)||!Array.isArray(data.comments))throw Error('项目／版本／审阅者不匹配');let seen=new Set();for(let c of data.comments){let a=arts.find(a=>a.artifact_id===c.artifact_id),r=arts.find(a=>a.artifact_id===c.reference_artifact_id);if(c.project_id!==P.project_id||!a||a.sha256!==c.artifact_sha256||!knownLocator(a,c.locator)||!r||r.sha256!==c.reference_sha256||!knownLocator(r,c.reference_locator)||typeof c.text!=='string'||c.text.length>100000||!c.updated_at||!Number.isFinite(Date.parse(c.updated_at)))throw Error('未知产物、过期哈希或无效定位');if(seen.has(key(c)))throw Error('重复目标冲突');seen.add(key(c));}return data.comments;}
function fill(select,values){select.replaceChildren(...values.map(v=>{let o=document.createElement('option');o.value=v.value;o.textContent=v.label;return o;}));}
function positions(side){const a=artifact(side);let rows=a.pages.map((p,i)=>({p,i}));if(side==='right')rows=rows.filter(({p})=>{let q=$('#quality').value,c=$('#commentFilter').value,e=$('#errorFilter').value;let has=comments.some(c=>c.artifact_id===a.artifact_id&&c.artifact_sha256===a.sha256&&stable(c.locator)===stable(p.locator)&&c.text);return (!q||(p.quality||'unknown')===q)&&(!c||(c==='yes')===!!has)&&(!e||(e==='yes')===!!p.error);});fill($('#'+side+'Position'),rows.length?rows.map(({p,i})=>({value:i,label:p.label})): [{value:-1,label:a.pages.length?'无匹配位置':'整份文档'}]);}
function link(container,path,label){let a=document.createElement('a');a.href='../'+path;a.textContent=label;a.target='_blank';a.rel='noopener';container.append(a,document.createElement('br'));}
function showData(side,data,token){if(token!==tokens[side])return;let box=$('#'+side+'Content');if(data.quality){let q=document.createElement('div');q.className='quality';q.textContent='模型质量自评（未经人工确认）：'+data.quality.overall_quality+'；建议 '+data.quality.suggested_action+'。 '+(data.quality.evidence||[]).join('；');box.append(q);}let pre=document.createElement('pre');pre.textContent=data.text||'没有正文输出。';box.append(pre);if(data.raw_path){let d=document.createElement('details'),s=document.createElement('summary');s.textContent='原始响应与调用资料';d.append(s);link(d,data.raw_path,'打开原始响应');box.append(d);}}
function render(side){let token=++tokens[side],a=artifact(side),p=position(side),box=$('#'+side+'Content'),n=$('#'+side+'Notice');box.replaceChildren();n.textContent=a.name+' · '+(p.label||'文档级')+'。'+a.mapping_note;if(a.path)link(box,a.path,'打开／下载原文件');if(a.external_reference){n.textContent+=' 外部原件仅引用，不在包内；离线／目录移动后可能不可访问。现有预览可独立查看。';let d=document.createElement('details'),s=document.createElement('summary');s.textContent='原件引用（不自动访问）';d.append(s,document.createTextNode(a.external_reference.path));box.append(d);}if(a.preview?.label)n.textContent+=' '+a.preview.label;
if(Number($('#'+side+'Position').value)===-1&&a.pages.length){n.textContent+=' 无匹配结果。';return;}
if(p.image){let im=document.createElement('img');im.src='../'+p.image;im.alt=p.label;im.onerror=()=>{n.textContent+=' 预览不可用，请打开原文件。';};box.append(im);link(box,p.image,'新窗口放大原图／预览');}
else if(p.pdf||a.format==='pdf'){let obj=document.createElement('object');obj.type='application/pdf';obj.data='../'+(p.pdf||a.path)+'#page='+(p.output_page||1);obj.textContent='浏览器 PDF 预览不可用，请使用上方打开／下载入口。';box.append(obj);n.textContent+=' 浏览器可能不支持内嵌 PDF；可打开原文件。';}
else if(!p.data)n.textContent+=' 没有可用预览；支持文档级评论，Word不能在浏览器原生显示。';
if(p.data){loading=loading.then(()=>new Promise(resolve=>{if(token!==tokens[side]){resolve();return;}let script=document.createElement('script');script.src='../'+p.data;script.onload=()=>{showData(side,window.PROJECT_PAGE,token);delete window.PROJECT_PAGE;script.remove();resolve();};script.onerror=()=>{n.textContent+=' 文本资源缺失。';script.remove();resolve();};document.head.append(script);}));}}
function refresh(side){loadComment();if(!side||side==='left')render('left');if(!side||side==='right')render('right');$('#technical').textContent=JSON.stringify({project_id:P.project_id,revision:P.revision,target:artifact('right'),reference:artifact('left'),templates:P.templates},null,2);}
$('#title').textContent=P.name;
for(let side of ['left','right']){fill($('#'+side+'Artifact'),arts.map(a=>({value:a.artifact_id,label:a.name+' ('+a.format+' v'+a.version+')'})));$('#'+side+'Artifact').onchange=()=>{save();positions(side);refresh(side);};$('#'+side+'Position').onchange=()=>{save();refresh(side);};}
$('#rightArtifact').selectedIndex=Math.min(1,arts.length-1);
try{feedbackBase=Number(localStorage.getItem(storageKey+':base')||0);let saved=JSON.parse(localStorage.getItem(storageKey)||'[]');comments=validate({schema:'filetools-artifact-feedback-v1',project_id:P.project_id,project_revision:P.revision,reviewer_type:'human',comments:saved});}catch{notice('旧草稿不匹配，未导入；请保留原导出记录。');}
for(let id of ['quality','commentFilter','errorFilter'])$('#'+id).onchange=()=>{save();positions('right');refresh('right');};
$('#comment').oninput=save;
$('#mobile').onclick=()=>{save();document.body.classList.toggle('result');};
$('#export').onclick=()=>{save();let data={schema:'filetools-artifact-feedback-v1',project_id:P.project_id,project_revision:P.revision,reviewer_type:$('#reviewer').value,base_feedback_revision:feedbackBase,comments};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='feedback-'+P.project_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{save();try{let input=JSON.parse(await e.target.files[0].text());let wrapped=!!input.receipt;let imported=validate(wrapped?input.receipt:input);let base=wrapped?input.revision:(input.base_feedback_revision||0);if(!Number.isInteger(base)||base<0)throw Error('回执版本无效');for(let c of imported){let old=comments.find(o=>key(o)===key(c));if(old&&stable(old)!==stable(c))throw Error('与本地草稿冲突，未导入');}for(let c of imported)if(!comments.some(o=>key(o)===key(c)))comments.push(c);feedbackBase=base;localStorage.setItem(storageKey+':base',String(base));localStorage.setItem(storageKey,JSON.stringify(comments));loadComment();notice('导入成功（评论不是验收）。');}catch(err){notice('拒绝导入：'+err.message);}e.target.value='';};
window.addEventListener('beforeunload',save);positions('left');positions('right');refresh();
