'use strict';
const P=window.PROJECT, $=s=>document.querySelector(s), arts=P.artifacts;
const requestedView=new URLSearchParams(location.search);let viewReady=false;
const storageKey='filetools-feedback:'+P.project_id;
let feedbackBase=0, comments=[], loading=Promise.resolve(), tokens={left:0,right:0};
const notice=s=>{$('#status').textContent=s;};
function stable(x){if(Array.isArray(x))return '['+x.map(stable).join(',')+']';if(x&&typeof x==='object')return '{'+Object.keys(x).sort().map(k=>JSON.stringify(k)+':'+stable(x[k])).join(',')+'}';return JSON.stringify(x);}
function artifact(side){return arts.find(a=>a.artifact_id===$('#'+side+'Artifact').value);}
function position(side){let a=artifact(side);return a.pages[Number($('#'+side+'Position').value)]||{locator:{kind:'document'}};}
function identity(){let original=$('#commentScope').value==='source_page',a=original?source:artifact('right'),r=artifact('left'),loc=original?(source.pages[Number($('#sourcePosition').value)]||{}).locator:position('right').locator;if(!loc)return null;return {object_type:original?'source_page':'artifact',project_id:P.project_id,artifact_id:a.artifact_id,artifact_sha256:a.sha256,locator:loc,reference_artifact_id:r.artifact_id,reference_sha256:r.sha256,reference_locator:position('left').locator};}
function key(c){return stable([c.object_type||'artifact',c.artifact_id,c.artifact_sha256,c.locator]);}

const serverMode=location.protocol==='http:'||location.protocol==='https:';
const feedbackURL='/api/projects/'+P.project_id+'/feedback';
let serverReady=!serverMode,saveTimer=null,saving=false,dirty=false,pendingImport=null;
function receipt(){return {schema:'filetools-artifact-feedback-v1',project_id:P.project_id,project_revision:P.revision,reviewer_type:$('#reviewer').value,base_feedback_revision:feedbackBase,comments};}
function downloadReceipt(){let data=new Blob([JSON.stringify(receipt(),null,2)],{type:'application/json'}),url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download='feedback-'+P.project_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
function queueServerSave(){dirty=true;if(!serverMode)return;clearTimeout(saveTimer);saveTimer=setTimeout(flushServer,500);}
async function flushServer(){if(!serverMode||!serverReady||saving||!dirty)return;saving=true;dirty=false;try{let r=await fetch(feedbackURL,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(receipt())});let data=await r.json();if(!r.ok)throw Error(data.reason||data.error);feedbackBase=data.revision;localStorage.setItem(storageKey+':base',String(feedbackBase));notice('评语已保存到服务（不代表验收）。');}catch(e){dirty=true;serverReady=false;notice('服务保存失败／版本冲突：'+e.message+'。请导出草稿并重新加载，未覆盖服务记录。');}finally{saving=false;if(dirty&&serverReady)queueServerSave();}}
$('#saveServer').hidden=!serverMode;$('#saveServer').onclick=()=>{save();dirty=true;flushServer();};
$('#clearComment').onclick=()=>{$('#comment').value='';save();notice('当前评论已清除；历史回执仍保留。');};
$('#resolveImport').onclick=()=>{if(!pendingImport)return;downloadReceipt();let incoming=pendingImport;for(let c of incoming.comments){let i=comments.findIndex(o=>key(o)===key(c));if(i<0)comments.push(c);else comments[i]=c;}pendingImport=null;serverReady=true;$('#resolveImport').hidden=true;localStorage.setItem(storageKey,JSON.stringify(comments));loadComment();queueServerSave();notice('已采用导入版本，原草稿已导出备份。');};

let active=null;
function save(){if(!active)return;let i=comments.findIndex(c=>key(c)===key(active)),text=$('#comment').value;if(i>=0&&comments[i].text===text)return;if(i<0&&!text.trim())return;if(!text.trim())text='';let c={...active,text,updated_at:new Date().toISOString()};if(i<0)comments.push(c);else comments[i]=c;try{localStorage.setItem(storageKey,JSON.stringify(comments));notice(serverMode?'草稿已存本机，等待保存到服务。':'草稿已存本机；请导出备份。');queueServerSave();}catch{notice('浏览器存储不可用，请导出备份。');}}
function loadComment(){active=identity();$('#comment').value=active?(comments.find(c=>key(c)===key(active))||{}).text||'':'';$('#comment').disabled=!active||(serverMode&&!serverReady);$('#commentTargetLabel').textContent=active?(active.object_type==='source_page'?'原图 · '+($('#sourcePosition').selectedOptions[0]?.textContent||''):'产物 · '+(artifact('right').display_name||artifact('right').name)):'没有可评论的原图位置';}
function knownLocator(a,l){return l&& (stable(l)===stable({kind:'document'})||[...a.pages,...(a.legacy_pages||[])].some(p=>stable(p.locator)===stable(l)));}
function validate(data){if(data.schema!=='filetools-artifact-feedback-v1'||data.project_id!==P.project_id||data.project_revision!==P.revision||!['human','developer-agent'].includes(data.reviewer_type)||!Array.isArray(data.comments))throw Error('项目／版本／审阅者不匹配');let seen=new Set();for(let c of data.comments){let a=arts.find(a=>a.artifact_id===c.artifact_id),r=arts.find(a=>a.artifact_id===c.reference_artifact_id);if(!['artifact','source_page'].includes(c.object_type||'artifact')||(c.object_type==='source_page'&&(c.artifact_id!==source.artifact_id||!['physical_page','source_page'].includes(c.locator?.kind)))||c.project_id!==P.project_id||!a||a.sha256!==c.artifact_sha256||!knownLocator(a,c.locator)||(c.reference_artifact_id&&(!r||r.sha256!==c.reference_sha256||!knownLocator(r,c.reference_locator)))||typeof c.text!=='string'||c.text.length>100000||!c.updated_at||!Number.isFinite(Date.parse(c.updated_at)))throw Error('未知产物、过期哈希或无效定位');if(seen.has(key(c)))throw Error('重复目标冲突');seen.add(key(c));}return data.comments;}
function label(text){return String(text||'').replace(/SUCCEEDED/g,'已完成').replace(/PARTIAL/g,'部分完成').replace(/FAILED/g,'失败').replace(/RUNNING/g,'处理中').replace(/QUEUED/g,'排队中').replace(/INTERRUPTED/g,'中断');}
function fill(select,values){select.replaceChildren(...values.map(v=>{let o=document.createElement('option');o.value=v.value;o.textContent=label(v.label);return o;}));}
const source=arts.find(a=>a.artifact_id===P.source_artifact_id)||arts[0],evaluations=P.source_evaluations||[];
const uiKey='filetools-view:'+P.project_id;let selectedEvaluations={};
const qualityNames={good:'能直接辨读',usable_with_defects:'局部模糊或缺损',poor:'关键文字难辨',undetermined:'无法判断',unknown:'未提供评价'};
function records(p){return evaluations.filter(e=>e.source_artifact_id===source.artifact_id&&stable(e.source_locator)===stable(p.locator)&&(e.source_sha256===source.sha256||[p.image_sha256,p.recognition_image_sha256].includes(e.submitted_image?.sha256)));}
function assessment(p){let rows=records(p);return rows.find(e=>e.evaluation_id===selectedEvaluations[stable(p.locator)])||rows.at(-1);}
function sourceRows(){return source.pages.map((p,i)=>({p,i})).filter(({p})=>!$('#quality').value||($('#quality').value===(assessment(p)?.quality.overall_quality||'unknown')));}
function sourcePositions(){let old=$('#sourcePosition').value,rows=sourceRows();fill($('#sourcePosition'),rows.length?rows.map(({p,i})=>({value:i,label:p.label+(source.physical_index&&!serverMode?(p.image?' · 已缓存':' · 未缓存，仅在线'):'')})): [{value:-1,label:'没有匹配原图'}]);if([...$('#sourcePosition').options].some(o=>o.value===old))$('#sourcePosition').value=old;qualityPanel();}
function qualityPanel(){let page=source.pages[Number($('#sourcePosition').value)],rows=page?records(page):[],record=page?assessment(page):null;fill($('#evaluation'),rows.length?rows.map((e,i)=>({value:e.evaluation_id,label:(e.model||'未知模型')+' · '+(e.assessed_at||'时间未知')+' · 记录'+(i+1)})):[{value:'',label:'没有可核实关联的评价'}]);if(record)$('#evaluation').value=record.evaluation_id;$('#qualitySummary').textContent='原图评价：'+qualityNames[record?.quality.overall_quality||'unknown'];$('#qualityEvidence').textContent=record?((record.quality.evidence||[]).join('；')+' '+(record.quality.uncertainty_note||'')):'未提供或来源无法核实；不等于质量差。';}
function positions(side){const a=artifact(side);let rows=a.artifact_id===source.artifact_id?sourceRows():a.pages.map((p,i)=>({p,i}));if(side==='right'&&a.artifact_id!==source.artifact_id)rows=rows.filter(({p})=>{let c=$('#commentFilter').value,e=$('#errorFilter').value,has=comments.some(c=>(c.object_type||'artifact')==='artifact'&&c.artifact_id===a.artifact_id&&c.artifact_sha256===a.sha256&&stable(c.locator)===stable(p.locator)&&c.text);return (!c||(c==='yes')===!!has)&&(!e||(e==='yes'?!!p.error:e==='no'?!p.error:p.error_category===e));});fill($('#'+side+'Position'),rows.length?rows.map(({p,i})=>({value:i,label:p.label+(a.physical_index&&!serverMode?(p.image?' · 已缓存':' · 未缓存，仅在线'):'')})): [{value:-1,label:a.pages.length?'无匹配位置':'整份文档'}]);}
function link(container,path,label){let a=document.createElement('a');a.href='../'+path;a.textContent=label;a.target='_blank';a.rel='noopener';container.append(a);return a;}
function showData(side,data,token){if(token!==tokens[side])return;let box=$('#'+side+'Content');let pre=document.createElement('pre');pre.textContent=data.text||'没有正文输出。';if($('#markdownMode').value==='reading'&&data.reading_html){let div=document.createElement('div');div.className='reading';let parsed=new DOMParser().parseFromString(data.reading_html,'text/html');for(let node of parsed.body.querySelectorAll('*')){if(!['P','B','I','BR','H1','H2','H3'].includes(node.tagName)){node.replaceWith(document.createTextNode(node.textContent));continue;}for(let attr of [...node.attributes])node.removeAttribute(attr.name);}div.append(...parsed.body.childNodes);box.append(div);}else box.append(pre);zoom(side);if(data.raw_path){let d=document.createElement('details'),s=document.createElement('summary');s.textContent='原始响应与调用资料';d.append(s);link(d,data.raw_path,'打开诊断');box.append(d);}}
function persistView(){let v={selectedEvaluations,collapsed:document.body.classList.contains('toolbar-collapsed'),focus:document.body.dataset.focus||''};for(let id of ['leftArtifact','rightArtifact','leftPosition','rightPosition','leftZoom','rightZoom','sourcePosition','quality','commentScope','errorFilter','commentFilter','markdownMode'])v[id]=$('#'+id).value;localStorage.setItem(uiKey,JSON.stringify(v));if(viewReady&&!linkError){let q=new URLSearchParams();for(let side of ['left','right']){q.set(side,artifact(side).artifact_id);q.set(side+'_location',JSON.stringify(position(side).locator));}history.replaceState(null,'',location.pathname+'?'+q.toString());}}
function previewAction(box,a){let state=a.preview_render?.status||'NONE',d=document.createElement('div');d.className='placeholder';let labels={QUEUED:'预览排队中',RUNNING:'正在渲染逐页预览',FAILED:'预览失败',INTERRUPTED:'预览中断',NONE:'尚未生成逐页预览'};d.textContent=(labels[state]||'预览不可用')+(a.preview_render?.error?'：'+a.preview_render.error.code+' · '+a.preview_render.error.message:'');if(serverMode&&!['QUEUED','RUNNING'].includes(state)){let b=document.createElement('button');b.textContent='生成／重试真实预览';b.onclick=async()=>{save();await flushServer();persistView();let r=await fetch('/api/projects/'+P.project_id+'/previews/'+a.artifact_id,{method:'POST',headers:{'Content-Type':'application/json'},body:'{"retry":true}'});if(!r.ok){notice('预览请求失败');return;}notice('预览后台处理中，产物已保存。');let timer=setInterval(async()=>{let p=await(await fetch('/api/projects/'+P.project_id)).json(),state=p.artifacts.find(x=>x.artifact_id===a.artifact_id).preview_render.status;if(!['QUEUED','RUNNING'].includes(state)){clearInterval(timer);location.reload();}},1000);};d.append(b);}else if(!serverMode)d.append(document.createTextNode('；离线包不能运行渲染器，请在HTTP项目生成后重新导出。'));box.append(d);}
function zoom(side){let im=$('#'+side+'Content img');if(im)im.style.width=$('#'+side+'Zoom').value+'%';let pre=$('#'+side+'Content pre,#'+side+'Content .reading');if(pre)pre.style.fontSize=(14*Number($('#'+side+'Zoom').value)/100)+'px';persistView();}
function render(side){let token=++tokens[side],a=artifact(side),p=position(side),box=$('#'+side+'Content'),n=$('#'+side+'Notice');box.replaceChildren();n.textContent=label(p.label||'文档级')+' · '+(a.format==='docx'?'Word':a.format.toUpperCase());if(a.path){link(box,a.path,'打开原文件');let download=link(box,a.download_path||a.path,'下载');download.removeAttribute('target');download.download=a.download_name||a.name;if(serverMode)download.href='/api/projects/'+P.project_id+'/download/'+a.artifact_id;}if(a.external_reference){let d=document.createElement('details'),s=document.createElement('summary');s.textContent='外部原件未打包，可能不可访问；仅使用已有预览';d.append(s,document.createTextNode(a.external_reference.path));box.append(d);}if(Number($('#'+side+'Position').value)===-1&&a.pages.length){n.textContent+=' · 没有匹配位置';return;}
if(['docx','pdf'].includes(a.format)&&a.artifact_id!==source.artifact_id&&a.preview_render?.status!=='SUCCEEDED'){previewAction(box,a);return;}
if(a.artifact_id===source.artifact_id&&a.physical_index&&p.physical_page){renderOriginal(side,a,p,token,box,n);return;}
if(p.image){let im=document.createElement('img');im.src='../'+p.image;im.alt=p.label||'逐页预览';im.loading='eager';im.onerror=()=>{n.textContent+=' · 页面预览读取失败';};box.append(im);zoom(side);}else if(['pdf','docx'].includes(a.format)){previewAction(box,a);}else if(!p.data)n.textContent+=' · 无页面预览，可评论整份文档';
if(p.data){loading=loading.then(()=>new Promise(resolve=>{if(token!==tokens[side]){resolve();return;}let script=document.createElement('script');script.src='../'+p.data;script.onload=()=>{showData(side,window.PROJECT_PAGE,token);delete window.PROJECT_PAGE;script.remove();resolve();};script.onerror=()=>{n.textContent+=' · 文本资源缺失';script.remove();resolve();};document.head.append(script);}));}}

async function renderOriginal(side,a,p,token,box,n,retry=false,busyAttempt=0){
 const fresh=()=>token===tokens[side]&&artifact(side).artifact_id===a.artifact_id&&position(side).physical_page===p.physical_page;
 function show(image){if(!fresh())return;box.querySelector('.source-loading')?.remove();let im=document.createElement('img');im.src='../'+image;im.alt='原件物理第'+p.physical_page+'页';im.onerror=()=>{if(fresh())failure('缓存图片读取失败');};box.append(im);zoom(side);}
 function failure(text){if(!fresh())return;box.querySelector('.source-loading')?.remove();let d=document.createElement('div');d.className='placeholder source-loading';d.textContent=text; if(serverMode){let b=document.createElement('button');b.textContent='重试本页预览';b.onclick=()=>{d.remove();renderOriginal(side,a,p,token,box,n,true);};d.append(b);}box.append(d);}
 if(!serverMode){if(p.image)show(p.image);else failure('本页未缓存，离线包无法生成预览。请在线打开本项目按需浏览后重新导出。'+(!a.path?'外部原件未打包。':''));return;}
 let d=document.createElement('div');d.className='placeholder source-loading';d.textContent='正在加载原件第'+p.physical_page+'页…';box.append(d);
 try{let r=await fetch('/api/projects/'+P.project_id+'/source-preview/'+p.physical_page,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({retry})}),data=await r.json();if(!fresh())return;if(!r.ok)throw Error(data.reason||data.error);if(data.status==='BUSY'&&busyAttempt<100){d.remove();setTimeout(()=>{if(fresh())renderOriginal(side,a,p,token,box,n,retry,busyAttempt+1);},350);return;}if(data.status!=='SUCCEEDED'){failure(data.error?(data.error.code+'：'+data.error.message):(data.message||'预览未完成'));return;}p.image=data.image;p.image_sha256=data.image_sha256;show(p.image);}catch(e){failure('本页预览失败：'+e.message);}
}
function pageControls(side){let a=artifact(side),p=position(side),total=a.physical_index?.count||a.pages.length,input=$('#'+side+'PageInput');input.max=total;input.value=p.physical_page||p.output_page||Number($('#'+side+'Position').value)+1;$('#'+side+'PageTotal').textContent='/ 共'+total+'页';}
function jump(side,value){let a=artifact(side),n=Number(value),total=a.physical_index?.count||a.pages.length;if(!/^\d+$/.test(String(value))||!Number.isInteger(n)||n<1||n>total){notice('页码越界或无效，范围1–'+total);return;}let index=a.physical_index?n-1:n-1;if(![...$('#'+side+'Position').options].some(o=>o.value===String(index))){notice('该页被当前筛选排除，请先清除筛选');return;}$('#'+side+'Position').value=String(index);$('#'+side+'Position').dispatchEvent(new Event('change'));}

function updateTechnical(){if($('#technical').parentElement.open)$('#technical').textContent=JSON.stringify({project_id:P.project_id,target:artifact('right'),reference:artifact('left'),source_assessments:evaluations,unbound_legacy_quality:P.legacy_quality_records||[]},null,2);}
$('#technical').parentElement.ontoggle=updateTechnical;
function refresh(side){loadComment();if(!side||side==='left')render('left');if(!side||side==='right')render('right');updateTechnical();compactLabels();persistView();}
$('#title').textContent=P.name;
for(let side of ['left','right']){fill($('#'+side+'Artifact'),[source,...[...arts].reverse().filter(a=>a.artifact_id!==source.artifact_id)].filter(a=>!a.recycled&&['image','reference','markdown','docx','pdf'].includes(a.format)).map(a=>({value:a.artifact_id,label:(a.display_name||a.name)+(a.artifact_id===source.artifact_id?'':' · 第'+a.version+'版 · '+(a.display_metadata?.method||a.recognition_engine||''))})));$('#'+side+'Artifact').onchange=()=>{save();positions(side);refresh(side);};$('#'+side+'Position').onchange=()=>{save();if(artifact(side).artifact_id===source.artifact_id){$('#sourcePosition').value=$('#'+side+'Position').value;qualityPanel();}refresh(side);};$('#'+side+'Zoom').onchange=()=>zoom(side);}
$('#leftArtifact').value=source.artifact_id;$('#rightArtifact').value=[...arts].reverse().find(a=>a.format==='markdown'&&!a.recycled)?.artifact_id||source.artifact_id;
let restored={};try{restored=JSON.parse(localStorage.getItem(uiKey)||'{}');selectedEvaluations=restored.selectedEvaluations||{};}catch{}
for(let id of ['leftArtifact','rightArtifact','leftZoom','rightZoom','quality','commentScope','errorFilter','commentFilter','markdownMode'])if([...$('#'+id).options].some(o=>o.value===restored[id]))$('#'+id).value=restored[id];
sourcePositions();for(let side of ['left','right'])positions(side);
for(let id of ['leftPosition','rightPosition','sourcePosition'])if([...$('#'+id).options].some(o=>o.value===restored[id]))$('#'+id).value=restored[id];qualityPanel();
// Deep links override stored preferences, never infer output-page == original-page.
let linkError='';
for(let side of ['left','right']){let aid=requestedView.get(side);if(aid){let a=arts.find(a=>a.artifact_id===aid&&!a.recycled);if(!a||![...$('#'+side+'Artifact').options].some(o=>o.value===aid)){linkError+='链接中的'+(side==='right'?'目标':'参考')+'产物不存在或已回收。 ';continue;}$('#'+side+'Artifact').value=aid;$('#quality').value='';$('#errorFilter').value='';$('#commentFilter').value='';positions(side);let raw=requestedView.get(side+'_location');if(raw){try{let l=JSON.parse(raw),i=a.pages.findIndex(p=>stable(p.locator)===stable(l));if(i<0&&l.kind!=='document')throw Error();if(i>=0)$('#'+side+'Position').value=String(i);}catch{linkError+='定位链接失效，保留独立定位。 ';}}}}
if(requestedView.has('right')&&!requestedView.has('left_location')&&artifact('left').artifact_id===source.artifact_id){let a=artifact('right'),seen=new Set();function mapped(a){if(!a||a.artifact_id===source.artifact_id||seen.has(a.artifact_id))return [];seen.add(a.artifact_id);return [...a.pages.map(p=>p.source_page).filter(Number.isInteger),...(a.parents||[]).flatMap(id=>mapped(arts.find(x=>x.artifact_id===id)))];}let mappedPages=position('right').source_page?[position('right').source_page]:[...new Set(mapped(a))];if(mappedPages.length===1){let i=source.pages.findIndex(p=>p.physical_page===mappedPages[0]||p.locator?.kind==='physical_page'&&p.locator.page===mappedPages[0]);if(i>=0)$('#leftPosition').value=String(i);}}
sourcePositions();if(artifact('left').artifact_id===source.artifact_id)$('#sourcePosition').value=$('#leftPosition').value;viewReady=true;
if(linkError){let d=document.createElement('p');d.setAttribute('role','alert');d.textContent=linkError+'链接未定位成功；当前预览不代表请求版本，请重新选择。';document.querySelector('header').after(d);}
$('#sourcePosition').onchange=()=>{save();qualityPanel();if(artifact('left').artifact_id===source.artifact_id){$('#leftPosition').value=$('#sourcePosition').value;refresh('left');}else{loadComment();persistView();}};
$('#showSource').onclick=()=>{save();$('#leftArtifact').value=source.artifact_id;positions('left');$('#leftPosition').value=$('#sourcePosition').value;refresh('left');};
$('#evaluation').onchange=()=>{let p=source.pages[Number($('#sourcePosition').value)];if(p)selectedEvaluations[stable(p.locator)]=$('#evaluation').value;qualityPanel();persistView();};
$('#commentScope').onchange=()=>{save();loadComment();persistView();};
try{feedbackBase=Number(localStorage.getItem(storageKey+':base')||0);let saved=JSON.parse(localStorage.getItem(storageKey)||'[]');comments=validate({schema:'filetools-artifact-feedback-v1',project_id:P.project_id,project_revision:P.revision,reviewer_type:'human',comments:saved});}catch{notice('旧草稿不匹配，未导入；请保留原导出记录。');}
for(let id of ['commentFilter','errorFilter'])$('#'+id).onchange=()=>{save();positions('right');refresh('right');};
$('#comment').oninput=save;
$('#mobile').onclick=()=>{save();document.body.classList.toggle('result');};
$('#export').onclick=()=>{save();let data={schema:'filetools-artifact-feedback-v1',project_id:P.project_id,project_revision:P.revision,reviewer_type:$('#reviewer').value,base_feedback_revision:feedbackBase,comments};let blob=new Blob([JSON.stringify(data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='feedback-'+P.project_id+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
$('#import').onchange=async e=>{save();try{let input=JSON.parse(await e.target.files[0].text());let wrapped=!!input.receipt;let imported=validate(wrapped?input.receipt:input);let base=wrapped?input.revision:(input.base_feedback_revision||0);if(!Number.isInteger(base)||base<0)throw Error('回执版本无效');for(let c of imported){let old=comments.find(o=>key(o)===key(c));if(old&&stable(old)!==stable(c)){pendingImport={comments:imported};$('#resolveImport').hidden=false;throw Error('与草稿冲突；可明确选择使用导入版本，先备份');}}for(let c of imported)if(!comments.some(o=>key(o)===key(c)))comments.push(c);if(!serverMode)feedbackBase=base;localStorage.setItem(storageKey+':base',String(base));localStorage.setItem(storageKey,JSON.stringify(comments));loadComment();queueServerSave();notice('导入成功（评论不是验收）。');}catch(err){notice('拒绝导入：'+err.message);}e.target.value='';};
$('#quality').onchange=()=>{save();sourcePositions();for(let side of ['left','right'])if(artifact(side).artifact_id===source.artifact_id){positions(side);$('#'+side+'Position').value=$('#sourcePosition').value;render(side);}loadComment();persistView();};
function compactLabels(){for(let side of ['left','right']){pageControls(side);let name=$('#compact'+side[0].toUpperCase()+side.slice(1));name.textContent=artifact(side).display_name||artifact(side).name;name.title=name.textContent;let loc=position(side).locator,select=$('#'+side+'Position');$('#compact'+side[0].toUpperCase()+side.slice(1)+'Page').textContent=loc.kind==='output_page'?'第'+loc.page+'页':loc.kind==='physical_page'?'第'+loc.page+'页 / 共'+(source.physical_index?.count||source.pages.length)+'页':loc.kind==='document'?'整份':('位置'+(select.selectedIndex+1));}$('#toggleToolbar').textContent=document.body.classList.contains('toolbar-collapsed')?'展开工具栏':'收起工具栏';$('#focusLeft').textContent=document.body.dataset.focus==='left'?'恢复双栏':'专注左侧';$('#focusRight').textContent=document.body.dataset.focus==='right'?'恢复双栏':'专注右侧';}
let focusScroll=null;
function layoutChange(fn){save();let scroll=focusScroll||['left','right'].map(s=>({top:$('#'+s+'Pane').scrollTop,left:$('#'+s+'Pane').scrollLeft}));fn();compactLabels();requestAnimationFrame(()=>{['left','right'].forEach((s,i)=>{$('#'+s+'Pane').scrollTop=scroll[i].top;$('#'+s+'Pane').scrollLeft=scroll[i].left;});persistView();});return scroll;}
$('#toggleToolbar').onclick=()=>layoutChange(()=>{let before=document.querySelector('main').clientHeight;document.body.classList.toggle('toolbar-collapsed');let after=document.querySelector('main').clientHeight;document.body.style.setProperty('--fold-delta',Math.max(0,after-before)+'px');});
for(let side of ['left','right']){$('#focus'+side[0].toUpperCase()+side.slice(1)).onclick=()=>{let restoring=document.body.dataset.focus===side;let captured=layoutChange(()=>{document.body.classList.remove('focus-left','focus-right');document.body.dataset.focus=restoring?'':side;if(!restoring)document.body.classList.add('focus-'+side);});focusScroll=restoring?null:captured;};for(let [suffix,delta]of [['Prev',-1],['Next',1]])$('#compact'+side[0].toUpperCase()+side.slice(1)+suffix).onclick=()=>{let select=$('#'+side+'Position'),i=select.selectedIndex+delta;if(i>=0&&i<select.options.length){select.selectedIndex=i;select.dispatchEvent(new Event('change'));}};}
for(let side of ['left','right']){$('#'+side+'PageInput').onchange=e=>jump(side,e.target.value);$('#'+side+'PageInput').onkeydown=e=>{if(e.key==='Enter')jump(side,e.target.value);};for(let [suffix,delta]of [['PagePrev',-1],['PageNext',1]])$('#'+side+suffix).onclick=()=>jump(side,Number($('#'+side+'PageInput').value)+delta);}
$('#markdownMode').onchange=()=>{save();refresh();};
if(restored.collapsed)document.body.classList.add('toolbar-collapsed');if(['left','right'].includes(restored.focus)){document.body.dataset.focus=restored.focus;document.body.classList.add('focus-'+restored.focus);}compactLabels();
window.addEventListener('beforeunload',()=>{save();persistView();});refresh();

if(!serverMode&&window.PROJECT_FEEDBACK?.receipt){try{let data=window.PROJECT_FEEDBACK, imported=validate(data.receipt);feedbackBase=data.revision;for(let c of imported){let old=comments.find(o=>key(o)===key(c));if(old&&stable(old)!==stable(c)){pendingImport={comments:imported};$('#resolveImport').hidden=false;notice('离线包与本机草稿冲突；请明确选择，未覆盖。');break;}if(!old)comments.push(c);}$('#reviewer').value=data.receipt.reviewer_type;loadComment();}catch{notice('离线评论记录无效，未加载。');}}

if(serverMode){document.querySelector('header a').href='/projects/'+P.project_id;document.querySelector('header a').textContent='← 项目详情';$('#comment').disabled=true;fetch(feedbackURL).then(r=>r.json()).then(data=>{let serverComments=data.receipt?validate(data.receipt):[];feedbackBase=data.revision||0;for(let c of serverComments){let old=comments.find(o=>key(o)===key(c));if(old&&stable(old)!==stable(c)){pendingImport={comments:serverComments};$('#resolveImport').hidden=false;notice('服务与本机草稿不同；请导出备份后明确选择，未自动覆盖。');serverReady=false;$('#comment').disabled=false;return;}}for(let c of serverComments)if(!comments.some(o=>key(o)===key(c)))comments.push(c);serverReady=true;if(data.receipt)$('#reviewer').value=data.receipt.reviewer_type;$('#comment').disabled=false;loadComment();localStorage.setItem(storageKey+':base',String(feedbackBase));}).catch(()=>{notice('服务评论读取失败，本机草稿保留，请导出备份。');$('#comment').disabled=false;});}
